name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Global envni ishlatish
        run: echo $NODE_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install
