name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      -name: global envni ishlatish
      run: echo $NODE_ENV

      -name: Checkout repisitory
      uses: actions/checkout@v4

      name: Install dependensies
      run: pnpm install
